services:
  db:
    image: mariadb:lts-ubi10

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iam
      MYSQL_USER: iam
      MYSQL_PASSWORD: iam

    ports:
      - "3307:3306"

#    volumes:
#      - ./iam/mysql-init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  client:
    build: ./client
    ports:
      - "3000:3000"

  iam:
    build: ./iam
    ports:
      - "3001:80"
    depends_on:
      - db

  resource:
    build: ./resource
    ports:
      - "3002:80"
    depends_on:
      - db
      - redis