services:
  db:
    image: mariadb:lts-ubi10

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iam
      MYSQL_USER: iam
      MYSQL_PASSWORD: iam

    ports:
      - "3003:3306"

    volumes:
      - ./iam/mysql-init:/docker-entrypoint-initdb.d:ro,Z

    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h localhost -uroot -prootpassword" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "3004:6379"

  client:
    build: ./client
    ports:
      - "3000:3000"

  iam:
    build: ./iam
    ports:
      - "3001:80"
    depends_on:
      db:
        condition: service_healthy

  resource:
    build: ./resource
    ports:
      - "3002:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started